sudo: required
language: go
go: '1.13'
env:
  global:
    secure: WjK7Bf/VOa0HYlzWFYaZh8SsHdZAiiBWY30kJG78TJX/emm5AS+iinkrnN2aR9nuDbKmdbBffGS5PPvXrezaUZsXRRO/834CB1BCMteH+c7AtWLVpyy36K9ZSlztbe4rSiewkFof19tTGkRtHTbBz6eADUlaERFmpkab8aKZXInjtWbEanOJ7IeoJa/UyrOiqchAkGnbSpYQSz9ix9CfNsBPFcbaVJcKcL4d8iQfN1WgT2g8woQyEji+wyf3iq8b/KeoZOZR9H/LMhoifX2SPlJzPHoyoaAgq+OuIjUUYixX/qmX7hPx5s/IED0HOCYZD8SjZYnUNNYMyjLDbusQSo/tYl6mgUlgi7KItvGNroizqlI/guzQ1f/xZlkTAalPXtvuCKlLo1oSp0TmR0WcRnx6prcPrrxAae7l+1LUYaMHcOTtSwX+zpbPOrWW4hIt5HUskcNZjxFc+jJmCQz8SOaAPhZTVCL/XB8mFHwvomQvkqk83Us2KY9ZnkD304qjeHElpoTdTjw2mTySQdOKRrQ0+96wP0sgxW51c/lAXziA767DyiJWl6TX7PpBeUYCcGrfZ1NWJ59sZqWhu/NefSmN9BnuZ1bqpf5jVJ5lfqkewHX/cO0vVdcyaoxPWHzFVC0EbN5dhxlVuPuNzvMEOdEy8GFj8G2WqylA05Rx1yU=
services:
- docker
install:
- make tools
script:
- make golint test
before_deploy:
  - make build-x
notifications:
  slack:
    secure: gcT0X7a9IU5lYlVlLmVJAIoDZfT6V81F0pLtNMeg2iHCN08Mcgw6xDePj9Yrxnpg/wEi9X+9cLeVBrXk5H/MB/CdtWBs94evwSyq62/v9F5BvU1/MYu7cPHzM1EnsPWXagePew+YnDGAqcXyOfhK0UMawW6lErJLcbsNZJw9VkZFF258HGpRXXWFvVRAbIN1KMfIMoRzbMNfvhBWUJv5wAUiZHElg7mnIJ0ZETsbferpCo7wzAztBy4EwUM+Tqhv7s0COz4fnIQyMPSv7bz9/lvVh7m+GlVnVDOoEiSOaVhg+U1UvyZSyx2N1mxlrgEFqrewXVz1c/L4E71yS3/JIdbdSmq4kEzgrjz61eYrwh2yqlewMLHB6FTctbplodXLWqZBEtuX2SvbPc8uhyBDW+egz2e1AZ9R65ChnG4HWaQ5ZI/hBi1YGgeENCdxlasJVHGYeSL+yeNOummkUdRa8GvRAEoJ8HdEeaAqO1do9F1645X5VfpD2bt8gIKi+B/RmgCTNwRSwI2q4yXcaFrT+yy0dd+Qcz/oOoyqQL+NbOm5gmQdSk8mE3l0uqM3CTQFo1xNp4yYl6byYlhOV3b+6xK3zFD0ogGZJ83Z8n0ecyZGUnDnJv6uJ4hCjV4kWNgvbtJ59QCJt3iGWbapgW53lwYD0H00DRmf4/tBVFIRLGE=
deploy:
  provider: releases
  api_key: "$GITHUB_TOKEN"
  file_glob: true
  file: bin/*
  skip_cleanup: true
  name: "$TRAVIS_TAG"
  on:
    tags: true
